import pandas as pd
wars_data = [
    {
        "conflict_id": "HIST_1899_COL", 
        "conflict_name": "Guerra de los Mil Dias", 
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno de Colombia",
        "side_b": "Liberales rebeldes",
        "iso_a": "COL",
        "iso_b": "COL",
        "date_start": "1899-10-17",
        "date_end": "1902-11-21",
        "latitude": 4.7110,
        "longitude": -74.0721,
        "country": "Colombia",
        "region": "America Latina",
        "deaths_a": 80000,
        "deaths_b": 70000,
        "deaths_civilians": 50000,
        "deaths_unknown": 0,
        "best": 200000,
        "high": 250000,
        "low": 100000,
        "deaths_total": 200000,
        "length_of_conflict": 1131,
        "outcome": "Victoria gubernamental",
        "source_article": "https://es.wikipedia.org/wiki/Guerra_de_los_Mil_D%C3%ADas"
    },
    {
        "conflict_id": "HIST_1914_WW1",
        "conflict_name": "Primera Guerra Mundial",
        "type_of_conflict": "interstate",
        "side_a": "Aliados",
        "side_b": "Potencias Centrales",
        "iso_a": "GBR,FRA,RUS,USA",
        "iso_b": "DEU,AUT,OTTOMAN",
        "date_start": "1914-07-28",
        "date_end": "1918-11-11",
        "latitude": 50.8503,
        "longitude": 4.3517,
        "country": "Europa Occidental",
        "region": "Europa",
        "deaths_a": 5000000,
        "deaths_b": 4000000,
        "deaths_civilians": 7000000,
        "deaths_unknown": 0,
        "best": 21000000,
        "high": 22000000,
        "low": 15000000,
        "deaths_total": 21000000,
        "length_of_conflict": 1567,
        "outcome": "Victoria Aliada",
        "source_article": "https://es.wikipedia.org/wiki/Primera_Guerra_Mundial"
    },
    {
        "conflict_id": "HIST_1939_WW2",
        "conflict_name": "Segunda Guerra Mundial",
        "type_of_conflict": "interstate",
        "side_a": "Aliados",
        "side_b": "Potencias del Eje",
        "iso_a": "GBR,FRA,USA,URS,CHN",
        "iso_b": "DEU,ITA,JPN",
        "date_start": "1939-09-01",
        "date_end": "1945-09-02",
        "latitude": 52.5200,
        "longitude": 13.4050,
        "country": "Europa / Asia",
        "region": "Mundial",
        "deaths_a": 15000000,
        "deaths_b": 10000000,
        "deaths_civilians": 50000000,
        "deaths_unknown": 0,
        "best": 75000000,
        "high": 85000000,
        "low": 60000000,
        "deaths_total": 75000000,
        "length_of_conflict": 2193,
        "outcome": "Victoria Aliada",
        "source_article": "https://es.wikipedia.org/wiki/Segunda_Guerra_Mundial"
    },
    {
        "conflict_id": "HIST_1904_RJ",
        "conflict_name": "Guerra Ruso-Japonesa",
        "type_of_conflict": "interstate",
        "side_a": "Imperio Ruso",
        "side_b": "Imperio del Japon",
        "iso_a": "RUS",
        "iso_b": "JPN",
        "date_start": "1904-02-08",
        "date_end": "1905-09-05",
        "latitude": 43.1332,
        "longitude": 131.9000,
        "country": "Rusia / Japon",
        "region": "Asia",
        "deaths_a": 80000,
        "deaths_b": 47000,
        "deaths_civilians": 20000,
        "deaths_unknown": 0,
        "best": 147000,
        "high": 160000,
        "low": 130000,
        "deaths_total": 147000,
        "length_of_conflict": 574,
        "outcome": "Victoria japonesa",
        "source_article": "https://es.wikipedia.org/wiki/Guerra_ruso-japonesa"
    },
    {
        "conflict_id": "HIST_1910_MXREV",
        "conflict_name": "Revolucion Mexicana",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno de Porfirio Diaz",
        "side_b": "Revolucionarios mexicanos",
        "iso_a": "MEX",
        "iso_b": "MEX",
        "date_start": "1910-11-20",
        "date_end": "1920-05-21",
        "latitude": 19.4326,
        "longitude": -99.1332,
        "country": "Mexico",
        "region": "America Latina",
        "deaths_a": 200000,
        "deaths_b": 150000,
        "deaths_civilians": 300000,
        "deaths_unknown": 0,
        "best": 650000,
        "high": 1000000,
        "low": 500000,
        "deaths_total": 650000,
        "length_of_conflict": 3460,
        "outcome": "Cambio de regimen",
        "source_article": "https://es.wikipedia.org/wiki/Revoluci%C3%B3n_mexicana"
    },
    {
        "conflict_id": "HIST_502_SICILIES",
        "conflict_name": "First Two Sicilies",
        "type_of_conflict": "intrastate",
        "side_a": "Austria",
        "side_b": "Two Sicilies Liberals",
        "iso_a": "AUT",
        "iso_b": "ITA",
        "date_start": "1820-03-01",
        "date_end": "1821-03-24",
        "latitude": 40.8333,
        "longitude": 14.2500,
        "country": "Italy",
        "region": "Europa",
        "deaths_a": 500,
        "deaths_b": 2000,
        "deaths_civilians": 1000,
        "deaths_unknown": 0,
        "best": 3500,
        "high": 4000,
        "low": 2000,
        "deaths_total": 3500,
        "length_of_conflict": 388,
        "outcome": "Victoria austriaca",
        "source_article": "https://en.wikipedia.org/wiki/1820_Sicilian_rebellion"
    },
    {
        "conflict_id": "HIST_505_SARD",
        "conflict_name": "Sardinian Revolt",
        "type_of_conflict": "intrastate",
        "side_a": "Austria",
        "side_b": "Carbonari",
        "iso_a": "AUT",
        "iso_b": "ITA",
        "date_start": "1821-03-10",
        "date_end": "1821-04-20",
        "latitude": 39.2238,
        "longitude": 9.1217,
        "country": "Italy",
        "region": "Europa",
        "deaths_a": 300,
        "deaths_b": 500,
        "deaths_civilians": 200,
        "deaths_unknown": 0,
        "best": 1000,
        "high": 1500,
        "low": 800,
        "deaths_total": 1000,
        "length_of_conflict": 41,
        "outcome": "Fracaso revolucionario",
        "source_article": "https://en.wikipedia.org/wiki/Carbonari"
    },
    {
        "conflict_id": "HIST_506_GREEK",
        "conflict_name": "Greek Independence",
        "type_of_conflict": "intrastate",
        "side_a": "Ottoman Empire",
        "side_b": "Greeks",
        "iso_a": "TUR",
        "iso_b": "GRC",
        "date_start": "1821-03-25",
        "date_end": "1830-09-12",
        "latitude": 41.0082,
        "longitude": 28.9784,
        "country": "Greece",
        "region": "Europa",
        "deaths_a": 100000,
        "deaths_b": 90000,
        "deaths_civilians": 200000,
        "deaths_unknown": 0,
        "best": 390000,
        "high": 450000,
        "low": 300000,
        "deaths_total": 390000,
        "length_of_conflict": 3459,
        "outcome": "Independencia griega",
        "source_article": "https://en.wikipedia.org/wiki/Greek_War_of_Independence"
    },
    {
        "conflict_id": "HIST_507_EGYMEH",
        "conflict_name": "Egypt-Mehdi",
        "type_of_conflict": "intrastate",
        "side_a": "Egypt",
        "side_b": "Mehdi Army",
        "iso_a": "EGY",
        "iso_b": "SUD",
        "date_start": "1820-03-20",
        "date_end": "1822-05-01",
        "latitude": 30.0444,
        "longitude": 31.2357,
        "country": "Egypt",
        "region": "Africa",
        "deaths_a": 5000,
        "deaths_b": 7000,
        "deaths_civilians": 3000,
        "deaths_unknown": 0,
        "best": 15000,
        "high": 20000,
        "low": 10000,
        "deaths_total": 15000,
        "length_of_conflict": 772,
        "outcome": "Conflicto prolongado",
        "source_article": "https://en.wikipedia.org/wiki/Mahdist_War"
    },
    {
        "conflict_id": "HIST_508_JAN",
        "conflict_name": "Janissari Revolt",
        "type_of_conflict": "intrastate",
        "side_a": "Ottoman Empire",
        "side_b": "Janissaries",
        "iso_a": "TUR",
        "iso_b": "TUR",
        "date_start": "1826-06-14",
        "date_end": "1826-07-15",
        "latitude": 41.0082,
        "longitude": 28.9784,
        "country": "Turkey",
        "region": "Europa/Asia",
        "deaths_a": 500,
        "deaths_b": 6000,
        "deaths_civilians": 2000,
        "deaths_unknown": 0,
        "best": 8500,
        "high": 10000,
        "low": 7000,
        "deaths_total": 8500,
        "length_of_conflict": 31,
        "outcome": "Abolicion de los jenizaros",
        "source_article": "https://en.wikipedia.org/wiki/Auspicious_Event"
    },
        {
        "conflict_id": "HIST_510_MIG",
        "conflict_name": "Miguelite War",
        "type_of_conflict": "intrastate",
        "side_a": "Portugal",
        "side_b": "Constitutionalists",
        "iso_a": "PRT",
        "iso_b": "PRT",
        "date_start": "1828-07-11",
        "date_end": "1834-05-26",
        "latitude": 38.7169,
        "longitude": -9.1390,
        "country": "Portugal",
        "region": "Europa",
        "deaths_a": 12000,
        "deaths_b": 8000,
        "deaths_civilians": 15000,
        "deaths_unknown": 0,
        "best": 35000,
        "high": 40000,
        "low": 25000,
        "deaths_total": 35000,
        "length_of_conflict": 2145,
        "outcome": "Victoria constitucionalista",
        "source_article": "https://en.wikipedia.org/wiki/Liberal_Wars"
    },
    {
        "conflict_id": "HIST_511_MURID1",
        "conflict_name": "First Murid War",
        "type_of_conflict": "intrastate",
        "side_a": "Imperio Ruso",
        "side_b": "Ghazi Muhammad",
        "iso_a": "RUS",
        "iso_b": "CHE",
        "date_start": "1829-09-01",
        "date_end": "1832-06-15",
        "latitude": 55.7558,
        "longitude": 37.6173,
        "country": "Rusia",
        "region": "Caucaso",
        "deaths_a": 1000,
        "deaths_b": 500,
        "deaths_civilians": 1500,
        "deaths_unknown": 0,
        "best": 3000,
        "high": 5000,
        "low": 2000,
        "deaths_total": 3000,
        "length_of_conflict": 1018,
        "outcome": "Resistencia murid contenida",
        "source_article": "https://en.wikipedia.org/wiki/Caucasian_War"
    },
    {
        "conflict_id": "HIST_513_FRINS",
        "conflict_name": "First French Insurrection",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno de Francia",
        "side_b": "Liberales",
        "iso_a": "FRA",
        "iso_b": "FRA",
        "date_start": "1830-07-25",
        "date_end": "1830-07-29",
        "latitude": 48.8566,
        "longitude": 2.3522,
        "country": "Francia",
        "region": "Europa",
        "deaths_a": 400,
        "deaths_b": 1800,
        "deaths_civilians": 2000,
        "deaths_unknown": 0,
        "best": 4200,
        "high": 5000,
        "low": 3000,
        "deaths_total": 4200,
        "length_of_conflict": 4,
        "outcome": "Abdicacion de Carlos X",
        "source_article": "https://en.wikipedia.org/wiki/July_Revolution"
    },
    {
        "conflict_id": "HIST_515_BELG",
        "conflict_name": "Belgian Independence",
        "type_of_conflict": "intrastate",
        "side_a": "Paises Bajos",
        "side_b": "Belgas",
        "iso_a": "NLD",
        "iso_b": "BEL",
        "date_start": "1830-08-25",
        "date_end": "1831-11-21",
        "latitude": 52.3676,
        "longitude": 4.9041,
        "country": "Belgica",
        "region": "Europa",
        "deaths_a": 500,
        "deaths_b": 600,
        "deaths_civilians": 1500,
        "deaths_unknown": 0,
        "best": 2600,
        "high": 3000,
        "low": 2000,
        "deaths_total": 2600,
        "length_of_conflict": 453,
        "outcome": "Independencia belga",
        "source_article": "https://en.wikipedia.org/wiki/Belgian_Revolution"
    },
    {
        "conflict_id": "HIST_517_POL",
        "conflict_name": "First Polish",
        "type_of_conflict": "intrastate",
        "side_a": "Imperio Ruso",
        "side_b": "Polacos",
        "iso_a": "RUS",
        "iso_b": "POL",
        "date_start": "1830-11-29",
        "date_end": "1831-09-21",
        "latitude": 55.7558,
        "longitude": 37.6173,
        "country": "Polonia",
        "region": "Europa del Este",
        "deaths_a": 15000,
        "deaths_b": 20000,
        "deaths_civilians": 10000,
        "deaths_unknown": 0,
        "best": 45000,
        "high": 50000,
        "low": 30000,
        "deaths_total": 45000,
        "length_of_conflict": 297,
        "outcome": "Victoria rusa",
        "source_article": "https://en.wikipedia.org/wiki/November_Uprising"
    },
        {
        "conflict_id": "HIST_518_SYR1",
        "conflict_name": "First Syrian",
        "type_of_conflict": "intrastate",
        "side_a": "Imperio Otomano",
        "side_b": "Egipto (Muhammad Ali)",
        "iso_a": "TUR",
        "iso_b": "EGY",
        "date_start": "1831-11-01",
        "date_end": "1833-05-14",
        "latitude": 33.5138,
        "longitude": 36.2765,
        "country": "Siria",
        "region": "Medio Oriente",
        "deaths_a": 10000,
        "deaths_b": 8000,
        "deaths_civilians": 7000,
        "deaths_unknown": 0,
        "best": 25000,
        "high": 30000,
        "low": 20000,
        "deaths_total": 25000,
        "length_of_conflict": 560,
        "outcome": "Victoria egipcia",
        "source_article": "https://en.wikipedia.org/wiki/First_Turkish%E2%80%93Egyptian_War"
    },
    {
        "conflict_id": "HIST_519_EGYPALEST",
        "conflict_name": "Egypt-Palestinian Anti-Conscription Revolt",
        "type_of_conflict": "intrastate",
        "side_a": "Egipto",
        "side_b": "Rebeldes palestinos",
        "iso_a": "EGY",
        "iso_b": "PSE",
        "date_start": "1834-05-01",
        "date_end": "1834-08-15",
        "latitude": 31.7683,
        "longitude": 35.2137,
        "country": "Palestina",
        "region": "Medio Oriente",
        "deaths_a": 3000,
        "deaths_b": 5000,
        "deaths_civilians": 7000,
        "deaths_unknown": 0,
        "best": 15000,
        "high": 20000,
        "low": 12000,
        "deaths_total": 15000,
        "length_of_conflict": 106,
        "outcome": "Victoria egipcia",
        "source_article": "https://en.wikipedia.org/wiki/Peasants%27_revolt_in_Palestine"
    },
    {
        "conflict_id": "HIST_520_CARL1",
        "conflict_name": "First Carlist War",
        "type_of_conflict": "intrastate",
        "side_a": "Isabelinos (gobierno español)",
        "side_b": "Carlitas",
        "iso_a": "ESP",
        "iso_b": "ESP",
        "date_start": "1833-09-29",
        "date_end": "1840-08-31",
        "latitude": 42.8169,
        "longitude": -1.6432,
        "country": "España",
        "region": "Europa",
        "deaths_a": 50000,
        "deaths_b": 40000,
        "deaths_civilians": 30000,
        "deaths_unknown": 0,
        "best": 120000,
        "high": 150000,
        "low": 90000,
        "deaths_total": 120000,
        "length_of_conflict": 2530,
        "outcome": "Victoria isabelina",
        "source_article": "https://es.wikipedia.org/wiki/Primera_guerra_carlista"
    },
    {
        "conflict_id": "HIST_521_MURID2",
        "conflict_name": "Second Murid War",
        "type_of_conflict": "intrastate",
        "side_a": "Imperio Ruso",
        "side_b": "Imam Shamil",
        "iso_a": "RUS",
        "iso_b": "CHE",
        "date_start": "1834-01-01",
        "date_end": "1859-09-06",
        "latitude": 42.9831,
        "longitude": 47.5047,
        "country": "Caucaso Norte",
        "region": "Europa/Asia",
        "deaths_a": 20000,
        "deaths_b": 15000,
        "deaths_civilians": 40000,
        "deaths_unknown": 0,
        "best": 75000,
        "high": 100000,
        "low": 50000,
        "deaths_total": 75000,
        "length_of_conflict": 9361,
        "outcome": "Victoria rusa",
        "source_article": "https://en.wikipedia.org/wiki/Caucasian_War"
    },
    {
        "conflict_id": "HIST_522_CABANOS",
        "conflict_name": "Cabanos Revolt",
        "type_of_conflict": "intrastate",
        "side_a": "Imperio de Brasil",
        "side_b": "Rebeldes cabanos",
        "iso_a": "BRA",
        "iso_b": "BRA",
        "date_start": "1832-11-01",
        "date_end": "1835-06-24",
        "latitude": -9.6658,
        "longitude": -35.7350,
        "country": "Brasil",
        "region": "America Latina",
        "deaths_a": 2000,
        "deaths_b": 4000,
        "deaths_civilians": 3000,
        "deaths_unknown": 0,
        "best": 9000,
        "high": 12000,
        "low": 7000,
        "deaths_total": 9000,
        "length_of_conflict": 966,
        "outcome": "Victoria del Imperio",
        "source_article": "https://en.wikipedia.org/wiki/Cabanada"
    },
        {
        "conflict_id": "HIST_523_FARROUP",
        "conflict_name": "Farroupilha War",
        "type_of_conflict": "intrastate",
        "side_a": "Imperio de Brasil",
        "side_b": "Republica Rio-Grandense",
        "iso_a": "BRA",
        "iso_b": "BRA",
        "date_start": "1835-09-20",
        "date_end": "1845-03-01",
        "latitude": -30.0346,
        "longitude": -51.2177,
        "country": "Brasil",
        "region": "America Latina",
        "deaths_a": 10000,
        "deaths_b": 8000,
        "deaths_civilians": 5000,
        "deaths_unknown": 0,
        "best": 23000,
        "high": 30000,
        "low": 15000,
        "deaths_total": 23000,
        "length_of_conflict": 3452,
        "outcome": "Acuerdo de paz",
        "source_article": "https://en.wikipedia.org/wiki/Ragamuffin_War"
    },
    {
        "conflict_id": "HIST_524_TEXAN",
        "conflict_name": "Texan War of Independence",
        "type_of_conflict": "intrastate",
        "side_a": "Mexico",
        "side_b": "Texanos",
        "iso_a": "MEX",
        "iso_b": "USA",
        "date_start": "1835-10-02",
        "date_end": "1836-04-21",
        "latitude": 29.7604,
        "longitude": -95.3698,
        "country": "Texas",
        "region": "America del Norte",
        "deaths_a": 1000,
        "deaths_b": 700,
        "deaths_civilians": 300,
        "deaths_unknown": 0,
        "best": 2000,
        "high": 2500,
        "low": 1500,
        "deaths_total": 2000,
        "length_of_conflict": 202,
        "outcome": "Independencia de Texas",
        "source_article": "https://en.wikipedia.org/wiki/Texas_Revolution"
    },
    {
        "conflict_id": "HIST_525_BOSN1",
        "conflict_name": "First Bosnian Uprising",
        "type_of_conflict": "intrastate",
        "side_a": "Imperio Otomano",
        "side_b": "Bosnios rebeldes",
        "iso_a": "TUR",
        "iso_b": "BIH",
        "date_start": "1831-02-05",
        "date_end": "1832-05-31",
        "latitude": 43.8563,
        "longitude": 18.4131,
        "country": "Bosnia y Herzegovina",
        "region": "Europa del Este",
        "deaths_a": 2000,
        "deaths_b": 4000,
        "deaths_civilians": 1000,
        "deaths_unknown": 0,
        "best": 7000,
        "high": 9000,
        "low": 5000,
        "deaths_total": 7000,
        "length_of_conflict": 482,
        "outcome": "Represion otomana",
        "source_article": "https://en.wikipedia.org/wiki/Bosnian_uprising_(1831%E2%80%931832)"
    },
    {
        "conflict_id": "HIST_526_MURID3",
        "conflict_name": "Third Murid War",
        "type_of_conflict": "intrastate",
        "side_a": "Imperio Ruso",
        "side_b": "Muridins",
        "iso_a": "RUS",
        "iso_b": "CHE",
        "date_start": "1840-01-01",
        "date_end": "1859-09-06",
        "latitude": 43.0000,
        "longitude": 46.0000,
        "country": "Caucaso Norte",
        "region": "Europa/Asia",
        "deaths_a": 15000,
        "deaths_b": 12000,
        "deaths_civilians": 30000,
        "deaths_unknown": 0,
        "best": 57000,
        "high": 70000,
        "low": 40000,
        "deaths_total": 57000,
        "length_of_conflict": 7176,
        "outcome": "Victoria rusa",
        "source_article": "https://en.wikipedia.org/wiki/Caucasian_War"
    },
    {
        "conflict_id": "HIST_527_SABINADA",
        "conflict_name": "Sabinada Rebellion",
        "type_of_conflict": "intrastate",
        "side_a": "Imperio de Brasil",
        "side_b": "Rebeldes bahianos",
        "iso_a": "BRA",
        "iso_b": "BRA",
        "date_start": "1837-11-07",
        "date_end": "1838-03-16",
        "latitude": -12.9714,
        "longitude": -38.5014,
        "country": "Brasil",
        "region": "America Latina",
        "deaths_a": 800,
        "deaths_b": 1000,
        "deaths_civilians": 1200,
        "deaths_unknown": 0,
        "best": 3000,
        "high": 4000,
        "low": 2000,
        "deaths_total": 3000,
        "length_of_conflict": 129,
        "outcome": "Victoria del Imperio",
        "source_article": "https://en.wikipedia.org/wiki/Sabinada"
    },
        {
        "conflict_id": "HIST_528_GUAT",
        "conflict_name": "Guatemalan Civil War",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno de Guatemala",
        "side_b": "URNG (rebeldes de izquierda)",
        "iso_a": "GTM",
        "iso_b": "GTM",
        "date_start": "1960-11-13",
        "date_end": "1996-12-29",
        "latitude": 14.6349,
        "longitude": -90.5069,
        "country": "Guatemala",
        "region": "America Latina",
        "deaths_a": 20000,
        "deaths_b": 20000,
        "deaths_civilians": 60000,
        "deaths_unknown": 0,
        "best": 100000,
        "high": 150000,
        "low": 80000,
        "deaths_total": 100000,
        "length_of_conflict": 13165,
        "outcome": "Acuerdo de paz",
        "source_article": "https://en.wikipedia.org/wiki/Guatemalan_Civil_War"
    },
    {
        "conflict_id": "HIST_529_SALV",
        "conflict_name": "Salvadoran Civil War",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno de El Salvador",
        "side_b": "FMLN",
        "iso_a": "SLV",
        "iso_b": "SLV",
        "date_start": "1980-10-15",
        "date_end": "1992-01-16",
        "latitude": 13.6929,
        "longitude": -89.2182,
        "country": "El Salvador",
        "region": "America Latina",
        "deaths_a": 20000,
        "deaths_b": 10000,
        "deaths_civilians": 45000,
        "deaths_unknown": 0,
        "best": 75000,
        "high": 80000,
        "low": 60000,
        "deaths_total": 75000,
        "length_of_conflict": 4106,
        "outcome": "Acuerdo de Chapultepec",
        "source_article": "https://en.wikipedia.org/wiki/Salvadoran_Civil_War"
    },
    {
        "conflict_id": "HIST_530_NIC",
        "conflict_name": "Nicaraguan Civil War",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno Sandinista",
        "side_b": "Contras",
        "iso_a": "NIC",
        "iso_b": "NIC",
        "date_start": "1981-03-01",
        "date_end": "1990-04-25",
        "latitude": 12.1364,
        "longitude": -86.2514,
        "country": "Nicaragua",
        "region": "America Latina",
        "deaths_a": 15000,
        "deaths_b": 15000,
        "deaths_civilians": 30000,
        "deaths_unknown": 0,
        "best": 60000,
        "high": 70000,
        "low": 50000,
        "deaths_total": 60000,
        "length_of_conflict": 3338,
        "outcome": "Transicion politica",
        "source_article": "https://en.wikipedia.org/wiki/Nicaraguan_Revolution"
    },
    {
        "conflict_id": "HIST_531_PERU",
        "conflict_name": "Civil War in Peru",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno de Peru",
        "side_b": "Sendero Luminoso y MRTA",
        "iso_a": "PER",
        "iso_b": "PER",
        "date_start": "1980-05-17",
        "date_end": "2000-11-22",
        "latitude": -12.0464,
        "longitude": -77.0428,
        "country": "Peru",
        "region": "America Latina",
        "deaths_a": 5000,
        "deaths_b": 7000,
        "deaths_civilians": 5000,
        "deaths_unknown": 0,
        "best": 17000,
        "high": 20000,
        "low": 15000,
        "deaths_total": 17000,
        "length_of_conflict": 7492,
        "outcome": "Victoria gubernamental",
        "source_article": "https://en.wikipedia.org/wiki/Internal_conflict_in_Peru"
    },
    {
        "conflict_id": "HIST_532_HAITI",
        "conflict_name": "Civil War in Haiti",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno de Haiti",
        "side_b": "Rebeldes armados",
        "iso_a": "HTI",
        "iso_b": "HTI",
        "date_start": "1991-09-30",
        "date_end": "1994-10-15",
        "latitude": 18.5944,
        "longitude": -72.3074,
        "country": "Haiti",
        "region": "Caribe",
        "deaths_a": 2000,
        "deaths_b": 2000,
        "deaths_civilians": 4000,
        "deaths_unknown": 0,
        "best": 8000,
        "high": 10000,
        "low": 6000,
        "deaths_total": 8000,
        "length_of_conflict": 1111,
        "outcome": "Restauracion democratica con apoyo internacional",
        "source_article": "https://en.wikipedia.org/wiki/1991_Haitian_coup_d%27%C3%A9tat"
    },
        {
        "conflict_id": "HIST_533_NIGERIA",
        "conflict_name": "Nigerian Civil War (Biafra War)",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno de Nigeria",
        "side_b": "Estado de Biafra",
        "iso_a": "NGA",
        "iso_b": "NGA",
        "date_start": "1967-07-06",
        "date_end": "1970-01-15",
        "latitude": 6.5244,
        "longitude": 3.3792,
        "country": "Nigeria",
        "region": "Africa",
        "deaths_a": 50000,
        "deaths_b": 100000,
        "deaths_civilians": 2000000,
        "deaths_unknown": 0,
        "best": 2150000,
        "high": 3000000,
        "low": 1000000,
        "deaths_total": 2150000,
        "length_of_conflict": 923,
        "outcome": "Victoria gubernamental",
        "source_article": "https://en.wikipedia.org/wiki/Nigerian_Civil_War"
    },
    {
        "conflict_id": "HIST_534_CONGO",
        "conflict_name": "War in Congo (Kinshasa)",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno del Congo",
        "side_b": "Diversos grupos rebeldes",
        "iso_a": "COD",
        "iso_b": "COD",
        "date_start": "1998-08-02",
        "date_end": "2003-07-18",
        "latitude": -4.4419,
        "longitude": 15.2663,
        "country": "Republica Democratica del Congo",
        "region": "Africa",
        "deaths_a": 200000,
        "deaths_b": 300000,
        "deaths_civilians": 4200000,
        "deaths_unknown": 0,
        "best": 4700000,
        "high": 5000000,
        "low": 3000000,
        "deaths_total": 4700000,
        "length_of_conflict": 1806,
        "outcome": "Acuerdo de paz parcial",
        "source_article": "https://en.wikipedia.org/wiki/Second_Congo_War"
    },
    {
        "conflict_id": "HIST_535_SUDAN1",
        "conflict_name": "First Sudanese Civil War",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno de Sudan",
        "side_b": "Anya-Nya (rebeldes sureños)",
        "iso_a": "SDN",
        "iso_b": "SDN",
        "date_start": "1955-08-18",
        "date_end": "1972-03-12",
        "latitude": 15.5007,
        "longitude": 32.5599,
        "country": "Sudan",
        "region": "Africa",
        "deaths_a": 50000,
        "deaths_b": 70000,
        "deaths_civilians": 300000,
        "deaths_unknown": 0,
        "best": 420000,
        "high": 500000,
        "low": 200000,
        "deaths_total": 420000,
        "length_of_conflict": 6047,
        "outcome": "Acuerdo de Addis Abeba",
        "source_article": "https://en.wikipedia.org/wiki/First_Sudanese_Civil_War"
    },
    {
        "conflict_id": "HIST_536_ANGOLA",
        "conflict_name": "Angolan Civil War",
        "type_of_conflict": "intrastate",
        "side_a": "MPLA",
        "side_b": "UNITA",
        "iso_a": "AGO",
        "iso_b": "AGO",
        "date_start": "1975-11-11",
        "date_end": "2002-04-04",
        "latitude": -8.8390,
        "longitude": 13.2894,
        "country": "Angola",
        "region": "Africa",
        "deaths_a": 200000,
        "deaths_b": 200000,
        "deaths_civilians": 600000,
        "deaths_unknown": 0,
        "best": 1000000,
        "high": 1200000,
        "low": 800000,
        "deaths_total": 1000000,
        "length_of_conflict": 9622,
        "outcome": "Victoria del MPLA",
        "source_article": "https://en.wikipedia.org/wiki/Angolan_Civil_War"
    },
    {
        "conflict_id": "HIST_537_ERITREA",
        "conflict_name": "Eritrean War of Independence",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno de Etiopia",
        "side_b": "Eritrean People's Liberation Front",
        "iso_a": "ETH",
        "iso_b": "ERI",
        "date_start": "1961-09-01",
        "date_end": "1991-05-24",
        "latitude": 15.3229,
        "longitude": 38.9251,
        "country": "Eritrea",
        "region": "Africa",
        "deaths_a": 50000,
        "deaths_b": 70000,
        "deaths_civilians": 100000,
        "deaths_unknown": 0,
        "best": 220000,
        "high": 250000,
        "low": 150000,
        "deaths_total": 220000,
        "length_of_conflict": 10869,
        "outcome": "Independencia de Eritrea",
        "source_article": "https://en.wikipedia.org/wiki/Eritrean_War_of_Independence"
    },
    {
        "conflict_id": "HIST_538_SLE1",
        "conflict_name": "First Sierra Leone Civil War",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno de Sierra Leona",
        "side_b": "Revolutionary United Front (RUF)",
        "iso_a": "SLE",
        "iso_b": "SLE",
        "date_start": "1991-03-23",
        "date_end": "2002-01-18",
        "latitude": 8.4657,
        "longitude": -13.2317,
        "country": "Sierra Leone",
        "region": "Africa",
        "deaths_a": 10000,
        "deaths_b": 15000,
        "deaths_civilians": 40000,
        "deaths_unknown": 0,
        "best": 65000,
        "high": 100000,
        "low": 50000,
        "deaths_total": 65000,
        "length_of_conflict": 3943,
        "outcome": "Intervencion internacional y paz",
        "source_article": "https://en.wikipedia.org/wiki/Sierra_Leone_Civil_War"
    },
    {
        "conflict_id": "HIST_539_LIBERIA1",
        "conflict_name": "First Liberian Civil War",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno de Liberia",
        "side_b": "NPFL (Charles Taylor)",
        "iso_a": "LBR",
        "iso_b": "LBR",
        "date_start": "1989-12-24",
        "date_end": "1997-08-02",
        "latitude": 6.3156,
        "longitude": -10.8074,
        "country": "Liberia",
        "region": "Africa",
        "deaths_a": 50000,
        "deaths_b": 20000,
        "deaths_civilians": 70000,
        "deaths_unknown": 0,
        "best": 140000,
        "high": 200000,
        "low": 100000,
        "deaths_total": 140000,
        "length_of_conflict": 2778,
        "outcome": "Victoria de Charles Taylor",
        "source_article": "https://en.wikipedia.org/wiki/First_Liberian_Civil_War"
    },
    {
        "conflict_id": "HIST_540_SPAIN",
        "conflict_name": "Spanish Civil War",
        "type_of_conflict": "intrastate",
        "side_a": "Republica Española",
        "side_b": "Nacionalistas",
        "iso_a": "ESP",
        "iso_b": "ESP",
        "date_start": "1936-07-17",
        "date_end": "1939-04-01",
        "latitude": 40.4168,
        "longitude": -3.7038,
        "country": "España",
        "region": "Europa",
        "deaths_a": 200000,
        "deaths_b": 300000,
        "deaths_civilians": 500000,
        "deaths_unknown": 0,
        "best": 1000000,
        "high": 1200000,
        "low": 600000,
        "deaths_total": 1000000,
        "length_of_conflict": 989,
        "outcome": "Victoria nacionalista",
        "source_article": "https://en.wikipedia.org/wiki/Spanish_Civil_War"
    },
    {
        "conflict_id": "HIST_541_VIETNAM",
        "conflict_name": "Vietnam Civil War",
        "type_of_conflict": "intrastate",
        "side_a": "Vietnam del Sur",
        "side_b": "Vietnam del Norte (Viet Cong)",
        "iso_a": "VNM",
        "iso_b": "VNM",
        "date_start": "1955-11-01",
        "date_end": "1975-04-30",
        "latitude": 21.0278,
        "longitude": 105.8342,
        "country": "Vietnam",
        "region": "Asia",
        "deaths_a": 250000,
        "deaths_b": 500000,
        "deaths_civilians": 2000000,
        "deaths_unknown": 0,
        "best": 2750000,
        "high": 3500000,
        "low": 2000000,
        "deaths_total": 2750000,
        "length_of_conflict": 7090,
        "outcome": "Victoria comunista, reunificacion",
        "source_article": "https://en.wikipedia.org/wiki/Vietnam_War"
    },
    {
        "conflict_id": "HIST_542_INDONESIA",
        "conflict_name": "Indonesian Internal War",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno de Indonesia",
        "side_b": "Diversos movimientos rebeldes",
        "iso_a": "IDN",
        "iso_b": "IDN",
        "date_start": "1950-04-25",
        "date_end": "1962-08-12",
        "latitude": -6.2088,
        "longitude": 106.8456,
        "country": "Indonesia",
        "region": "Asia",
        "deaths_a": 20000,
        "deaths_b": 30000,
        "deaths_civilians": 50000,
        "deaths_unknown": 0,
        "best": 100000,
        "high": 150000,
        "low": 80000,
        "deaths_total": 100000,
        "length_of_conflict": 4497,
        "outcome": "Victoria gubernamental",
        "source_article": "https://en.wikipedia.org/wiki/Darul_Islam_rebellion"
    },
    {
        "conflict_id": "HIST_543_KASHMIR1",
        "conflict_name": "First Kashmir War",
        "type_of_conflict": "interstate",
        "side_a": "India",
        "side_b": "Pakistan",
        "iso_a": "IND",
        "iso_b": "PAK",
        "date_start": "1947-10-22",
        "date_end": "1949-01-01",
        "latitude": 34.0837,
        "longitude": 74.7973,
        "country": "Kashmir",
        "region": "Asia",
        "deaths_a": 1500,
        "deaths_b": 6000,
        "deaths_civilians": 1000,
        "deaths_unknown": 0,
        "best": 8500,
        "high": 10000,
        "low": 7000,
        "deaths_total": 8500,
        "length_of_conflict": 436,
        "outcome": "Acuerdo de alto al fuego",
        "source_article": "https://en.wikipedia.org/wiki/Indo-Pakistani_War_of_1947"
    },
    {
        "conflict_id": "HIST_544_LAOS",
        "conflict_name": "Civil War in Laos",
        "type_of_conflict": "intrastate",
        "side_a": "Reino de Laos",
        "side_b": "Pathet Lao",
        "iso_a": "LAO",
        "iso_b": "LAO",
        "date_start": "1959-08-13",
        "date_end": "1975-12-02",
        "latitude": 17.9757,
        "longitude": 102.6331,
        "country": "Laos",
        "region": "Asia",
        "deaths_a": 10000,
        "deaths_b": 20000,
        "deaths_civilians": 30000,
        "deaths_unknown": 0,
        "best": 60000,
        "high": 70000,
        "low": 40000,
        "deaths_total": 60000,
        "length_of_conflict": 5958,
        "outcome": "Victoria comunista",
        "source_article": "https://en.wikipedia.org/wiki/Laotian_Civil_War"
    },
    {
        "conflict_id": "HIST_545_RUSREV",
        "conflict_name": "Guerra Civil Rusa",
        "type_of_conflict": "intrastate",
        "side_a": "Ejercito Rojo (bolcheviques)",
        "side_b": "Ejercito Blanco",
        "iso_a": "RUS",
        "iso_b": "RUS",
        "date_start": "1917-11-07",
        "date_end": "1923-10-25",
        "latitude": 55.7558,
        "longitude": 37.6173,
        "country": "Rusia",
        "region": "Europa/Asia",
        "deaths_a": 500000,
        "deaths_b": 600000,
        "deaths_civilians": 7000000,
        "deaths_unknown": 0,
        "best": 8100000,
        "high": 10000000,
        "low": 7000000,
        "deaths_total": 8100000,
        "length_of_conflict": 2180,
        "outcome": "Victoria bolchevique",
        "source_article": "https://en.wikipedia.org/wiki/Russian_Civil_War"
    },
        {
        "conflict_id": "HIST_546_ARG",
        "conflict_name": "Guerra Civil Argentina",
        "type_of_conflict": "intrastate",
        "side_a": "Unitarios",
        "side_b": "Federales",
        "iso_a": "ARG",
        "iso_b": "ARG",
        "date_start": "1814-01-01",
        "date_end": "1880-12-31",
        "latitude": -34.6037,
        "longitude": -58.3816,
        "country": "Argentina",
        "region": "America Latina",
        "deaths_a": 10000,
        "deaths_b": 15000,
        "deaths_civilians": 20000,
        "deaths_unknown": 0,
        "best": 45000,
        "high": 60000,
        "low": 30000,
        "deaths_total": 45000,
        "length_of_conflict": 24372,
        "outcome": "Victoria del sector federal y posterior unificacion",
        "source_article": "https://es.wikipedia.org/wiki/Guerras_civiles_argentinas"
    },
        {
        "conflict_id": "HIST_547_VEN",
        "conflict_name": "Guerra Civil de Venezuela (1848–1849)",
        "type_of_conflict": "intrastate",
        "side_a": "Gobierno Liberal (Jose Tadeo Monagas)",
        "side_b": "Oposicion Conservadora",
        "iso_a": "VEN",
        "iso_b": "VEN",
        "date_start": "1848-03-24",
        "date_end": "1849-08-20",
        "latitude": 10.4806,
        "longitude": -66.9036,
        "country": "Venezuela",
        "region": "America Latina",
        "deaths_a": 2000,
        "deaths_b": 3000,
        "deaths_civilians": 5000,
        "deaths_unknown": 0,
        "best": 10000,
        "high": 12000,
        "low": 8000,
        "deaths_total": 10000,
        "length_of_conflict": 514,
        "outcome": "Victoria liberal, consolidacion del poder de Monagas",
        "source_article": "https://es.wikipedia.org/wiki/Guerra_Civil_de_Venezuela_(1848-1849)"
    },
        {
        "conflict_id": "INTER_001_FRANCO_PRUSSIAN",
        "conflict_name": "Franco-Prussian War",
        "type_of_conflict": "interstate",
        "side_a": "Imperio Frances",
        "side_b": "Confederacion Alemana del Norte / Reino de Prusia",
        "iso_a": "FRA",
        "iso_b": "DEU",
        "date_start": "1870-07-19",
        "date_end": "1871-05-10",
        "latitude": 48.8566,
        "longitude": 2.3522,
        "country": "Francia / Alemania",
        "region": "Europa",
        "deaths_a": 100000,
        "deaths_b": 87000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 187000,
        "high": 200000,
        "low": 150000,
        "deaths_total": 187000,
        "length_of_conflict": 296,
        "outcome": "Victoria alemana, creacion del Imperio Aleman",
        "source_article": "https://en.wikipedia.org/wiki/Franco-Prussian_War"
    },
    {
        "conflict_id": "INTER_002_RUSSO_TURKISH_1828",
        "conflict_name": "First Russo-Turkish War (1828–1829)",
        "type_of_conflict": "interstate",
        "side_a": "Imperio Ruso",
        "side_b": "Imperio Otomano",
        "iso_a": "RUS",
        "iso_b": "TUR",
        "date_start": "1828-04-26",
        "date_end": "1829-09-14",
        "latitude": 43.0000,
        "longitude": 25.0000,
        "country": "Balcanes / Caucaso",
        "region": "Europa/Asia",
        "deaths_a": 70000,
        "deaths_b": 80000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 150000,
        "high": 170000,
        "low": 120000,
        "deaths_total": 150000,
        "length_of_conflict": 506,
        "outcome": "Victoria rusa, Tratado de Adrianopolis",
        "source_article": "https://en.wikipedia.org/wiki/Russo-Turkish_War_(1828%E2%80%931829)"
    },
    {
        "conflict_id": "INTER_003_CHACO",
        "conflict_name": "Chaco War",
        "type_of_conflict": "interstate",
        "side_a": "Bolivia",
        "side_b": "Paraguay",
        "iso_a": "BOL",
        "iso_b": "PRY",
        "date_start": "1932-06-15",
        "date_end": "1935-06-12",
        "latitude": -20.0000,
        "longitude": -60.0000,
        "country": "Bolivia / Paraguay",
        "region": "America Latina",
        "deaths_a": 60000,
        "deaths_b": 40000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 100000,
        "high": 120000,
        "low": 80000,
        "deaths_total": 100000,
        "length_of_conflict": 1093,
        "outcome": "Victoria paraguaya",
        "source_article": "https://en.wikipedia.org/wiki/Chaco_War"
    },
    {
        "conflict_id": "INTER_004_SEVEN_WEEKS",
        "conflict_name": "Seven Weeks' War (Austro-Prussian War)",
        "type_of_conflict": "interstate",
        "side_a": "Austria y aliados",
        "side_b": "Prusia y aliados italianos",
        "iso_a": "AUT",
        "iso_b": "DEU",
        "date_start": "1866-06-14",
        "date_end": "1866-08-23",
        "latitude": 50.0755,
        "longitude": 14.4378,
        "country": "Bohemia / Alemania",
        "region": "Europa",
        "deaths_a": 25000,
        "deaths_b": 23000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 48000,
        "high": 50000,
        "low": 40000,
        "deaths_total": 48000,
        "length_of_conflict": 70,
        "outcome": "Victoria prusiana, exclusion de Austria de Alemania",
        "source_article": "https://en.wikipedia.org/wiki/Austro-Prussian_War"
    },
    {
        "conflict_id": "INTER_005_CRIMEAN",
        "conflict_name": "Crimean War",
        "type_of_conflict": "interstate",
        "side_a": "Imperio Ruso",
        "side_b": "Imperio Otomano, Reino Unido, Francia, Cerdeña",
        "iso_a": "RUS",
        "iso_b": "TUR/FRA/GBR/ITA",
        "date_start": "1853-10-16",
        "date_end": "1856-03-30",
        "latitude": 44.9521,
        "longitude": 34.1024,
        "country": "Crimea",
        "region": "Europa/Asia",
        "deaths_a": 20000,
        "deaths_b": 15000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 35000,
        "high": 50000,
        "low": 30000,
        "deaths_total": 35000,
        "length_of_conflict": 896,
        "outcome": "Victoria aliada, debilitamiento ruso",
        "source_article": "https://en.wikipedia.org/wiki/Crimean_War"
    },
        {
        "conflict_id": "INTER_006_SINO_JAPANESE_2",
        "conflict_name": "Second Sino-Japanese War",
        "type_of_conflict": "interstate",
        "side_a": "China (Republica de China)",
        "side_b": "Imperio del Japon",
        "iso_a": "CHN",
        "iso_b": "JPN",
        "date_start": "1937-07-07",
        "date_end": "1945-09-09",
        "latitude": 31.2304,
        "longitude": 121.4737,
        "country": "China",
        "region": "Asia",
        "deaths_a": 15000000,
        "deaths_b": 2500000,
        "deaths_civilians": 10000000,
        "deaths_unknown": 0,
        "best": 17500000,
        "high": 20000000,
        "low": 15000000,
        "deaths_total": 17500000,
        "length_of_conflict": 2986,
        "outcome": "Victoria aliada, rendicion japonesa",
        "source_article": "https://en.wikipedia.org/wiki/Second_Sino-Japanese_War"
    },
    {
        "conflict_id": "INTER_007_KOREA",
        "conflict_name": "Korean War",
        "type_of_conflict": "interstate",
        "side_a": "Corea del Norte y aliados",
        "side_b": "Corea del Sur, EE.UU. y ONU",
        "iso_a": "PRK",
        "iso_b": "KOR/USA/UNO",
        "date_start": "1950-06-25",
        "date_end": "1953-07-27",
        "latitude": 37.5665,
        "longitude": 126.9780,
        "country": "Corea",
        "region": "Asia",
        "deaths_a": 400000,
        "deaths_b": 500000,
        "deaths_civilians": 2000000,
        "deaths_unknown": 0,
        "best": 2900000,
        "high": 3000000,
        "low": 2500000,
        "deaths_total": 2900000,
        "length_of_conflict": 1128,
        "outcome": "Armisticio, frontera en el paralelo 38",
        "source_article": "https://en.wikipedia.org/wiki/Korean_War"
    },
    {
        "conflict_id": "INTER_008_IRAN_IRAQ",
        "conflict_name": "Iran–Iraq War",
        "type_of_conflict": "interstate",
        "side_a": "Iran",
        "side_b": "Irak",
        "iso_a": "IRN",
        "iso_b": "IRQ",
        "date_start": "1980-09-22",
        "date_end": "1988-08-20",
        "latitude": 33.3152,
        "longitude": 44.3661,
        "country": "Iran / Irak",
        "region": "Medio Oriente",
        "deaths_a": 500000,
        "deaths_b": 250000,
        "deaths_civilians": 500000,
        "deaths_unknown": 0,
        "best": 1250000,
        "high": 1500000,
        "low": 1000000,
        "deaths_total": 1250000,
        "length_of_conflict": 2890,
        "outcome": "Empate militar, alto al fuego ONU",
        "source_article": "https://en.wikipedia.org/wiki/Iran%E2%80%93Iraq_War"
    },
    {
        "conflict_id": "INTER_009_SIX_DAY",
        "conflict_name": "Six-Day War",
        "type_of_conflict": "interstate",
        "side_a": "Israel",
        "side_b": "Egipto, Jordania, Siria",
        "iso_a": "ISR",
        "iso_b": "EGY/JOR/SYR",
        "date_start": "1967-06-05",
        "date_end": "1967-06-10",
        "latitude": 31.7683,
        "longitude": 35.2137,
        "country": "Israel / Egipto / Jordania / Siria",
        "region": "Medio Oriente",
        "deaths_a": 1000,
        "deaths_b": 20500,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 21500,
        "high": 25000,
        "low": 20000,
        "deaths_total": 21500,
        "length_of_conflict": 6,
        "outcome": "Victoria israeli, ocupacion de territorios",
        "source_article": "https://en.wikipedia.org/wiki/Six-Day_War"
    },
    {
        "conflict_id": "INTER_010_ARAB_ISRAELI_1948",
        "conflict_name": "Second Arab–Israeli War (1948)",
        "type_of_conflict": "interstate",
        "side_a": "Israel",
        "side_b": "Egipto, Jordania, Siria, Irak, Libano",
        "iso_a": "ISR",
        "iso_b": "EGY/JOR/SYR/IRQ/LBN",
        "date_start": "1948-05-15",
        "date_end": "1949-03-10",
        "latitude": 31.7683,
        "longitude": 35.2137,
        "country": "Israel / Palestina",
        "region": "Medio Oriente",
        "deaths_a": 6000,
        "deaths_b": 14000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 20000,
        "high": 25000,
        "low": 15000,
        "deaths_total": 20000,
        "length_of_conflict": 299,
        "outcome": "Victoria israeli, consolidacion del Estado de Israel",
        "source_article": "https://en.wikipedia.org/wiki/1948_Arab%E2%80%93Israeli_War"
    },
        {
        "conflict_id": "INTER_011_AUSTRO_SARDINIAN",
        "conflict_name": "Austro-Sardinian War (1859)",
        "type_of_conflict": "interstate",
        "side_a": "Imperio Austriaco",
        "side_b": "Reino de Cerdeña y Francia",
        "iso_a": "AUT",
        "iso_b": "ITA/FRA",
        "date_start": "1859-04-26",
        "date_end": "1859-07-12",
        "latitude": 45.0703,
        "longitude": 7.6869,
        "country": "Italia",
        "region": "Europa",
        "deaths_a": 10000,
        "deaths_b": 9400,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 19400,
        "high": 20000,
        "low": 15000,
        "deaths_total": 19400,
        "length_of_conflict": 77,
        "outcome": "Victoria franco-sarda, impulso a la unificacion italiana",
        "source_article": "https://en.wikipedia.org/wiki/Second_Italian_War_of_Independence"
    },
    {
        "conflict_id": "INTER_012_PACIFIC",
        "conflict_name": "War of the Pacific",
        "type_of_conflict": "interstate",
        "side_a": "Chile",
        "side_b": "Peru y Bolivia",
        "iso_a": "CHL",
        "iso_b": "PER/BOL",
        "date_start": "1879-04-05",
        "date_end": "1883-10-20",
        "latitude": -20.0000,
        "longitude": -70.0000,
        "country": "Chile / Peru / Bolivia",
        "region": "America Latina",
        "deaths_a": 10000,
        "deaths_b": 9000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 19000,
        "high": 20000,
        "low": 15000,
        "deaths_total": 19000,
        "length_of_conflict": 1655,
        "outcome": "Victoria chilena, anexion de territorios",
        "source_article": "https://en.wikipedia.org/wiki/War_of_the_Pacific"
    },
    {
        "conflict_id": "INTER_013_YUGOSLAV",
        "conflict_name": "Yugoslav Wars",
        "type_of_conflict": "interstate",
        "side_a": "Republica Federal de Yugoslavia",
        "side_b": "Croacia, Bosnia, Eslovenia, Kosovo",
        "iso_a": "YUG",
        "iso_b": "HRV/BIH/SVN/KOS",
        "date_start": "1991-06-25",
        "date_end": "1995-12-14",
        "latitude": 44.8176,
        "longitude": 20.4569,
        "country": "Ex-Yugoslavia",
        "region": "Europa",
        "deaths_a": 5000,
        "deaths_b": 12200,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 17200,
        "high": 20000,
        "low": 15000,
        "deaths_total": 17200,
        "length_of_conflict": 1634,
        "outcome": "Disolucion de Yugoslavia",
        "source_article": "https://en.wikipedia.org/wiki/Yugoslav_Wars"
    },
    {
        "conflict_id": "INTER_014_FRANCO_AUSTRIAN_1805",
        "conflict_name": "Franco-Austrian War (1805)",
        "type_of_conflict": "interstate",
        "side_a": "Imperio Frances",
        "side_b": "Imperio Austriaco",
        "iso_a": "FRA",
        "iso_b": "AUT",
        "date_start": "1805-09-08",
        "date_end": "1805-12-02",
        "latitude": 48.2082,
        "longitude": 16.3738,
        "country": "Austria",
        "region": "Europa",
        "deaths_a": 6000,
        "deaths_b": 6000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 12000,
        "high": 15000,
        "low": 10000,
        "deaths_total": 12000,
        "length_of_conflict": 85,
        "outcome": "Victoria francesa en Austerlitz",
        "source_article": "https://en.wikipedia.org/wiki/War_of_the_Third_Coalition"
    },
    {
        "conflict_id": "INTER_015_CONFEDERATION",
        "conflict_name": "War of the Confederation",
        "type_of_conflict": "interstate",
        "side_a": "Chile y Confederacion Argentina",
        "side_b": "Confederacion Peru-Boliviana",
        "iso_a": "CHL/ARG",
        "iso_b": "PER/BOL",
        "date_start": "1836-12-28",
        "date_end": "1839-01-20",
        "latitude": -13.5319,
        "longitude": -71.9675,
        "country": "Peru / Bolivia",
        "region": "America Latina",
        "deaths_a": 4000,
        "deaths_b": 6000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 10000,
        "high": 12000,
        "low": 8000,
        "deaths_total": 10000,
        "length_of_conflict": 753,
        "outcome": "Victoria chileno-argentina, disolucion de la Confederacion Peru-Boliviana",
        "source_article": "https://en.wikipedia.org/wiki/War_of_the_Confederation"
    },
        {
        "conflict_id": "INTER_016_POLISH_SOVIET",
        "conflict_name": "Polish-Soviet War",
        "type_of_conflict": "interstate",
        "side_a": "Polonia",
        "side_b": "Rusia Sovietica",
        "iso_a": "POL",
        "iso_b": "RUS",
        "date_start": "1919-02-14",
        "date_end": "1921-03-18",
        "latitude": 52.2297,
        "longitude": 21.0122,
        "country": "Polonia / Bielorrusia / Ucrania",
        "region": "Europa del Este",
        "deaths_a": 5000,
        "deaths_b": 5000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 10000,
        "high": 15000,
        "low": 8000,
        "deaths_total": 10000,
        "length_of_conflict": 764,
        "outcome": "Victoria polaca, Tratado de Riga",
        "source_article": "https://en.wikipedia.org/wiki/Polish%E2%80%93Soviet_War"
    },
    {
        "conflict_id": "INTER_017_YOM_KIPPUR",
        "conflict_name": "Yom Kippur War",
        "type_of_conflict": "interstate",
        "side_a": "Israel",
        "side_b": "Egipto y Siria",
        "iso_a": "ISR",
        "iso_b": "EGY/SYR",
        "date_start": "1973-10-06",
        "date_end": "1973-10-25",
        "latitude": 30.8025,
        "longitude": 33.2355,
        "country": "Israel / Egipto / Siria",
        "region": "Medio Oriente",
        "deaths_a": 2800,
        "deaths_b": 7100,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 9900,
        "high": 12000,
        "low": 8000,
        "deaths_total": 9900,
        "length_of_conflict": 19,
        "outcome": "Victoria israeli inicial, negociacion en Camp David posterior",
        "source_article": "https://en.wikipedia.org/wiki/Yom_Kippur_War"
    },
    {
        "conflict_id": "INTER_018_RUSSO_TURKISH_1877",
        "conflict_name": "Second Russo-Turkish War (1877–1878)",
        "type_of_conflict": "interstate",
        "side_a": "Imperio Ruso",
        "side_b": "Imperio Otomano",
        "iso_a": "RUS",
        "iso_b": "TUR",
        "date_start": "1877-04-24",
        "date_end": "1878-03-03",
        "latitude": 43.0000,
        "longitude": 25.0000,
        "country": "Balcanes / Caucaso",
        "region": "Europa/Asia",
        "deaths_a": 5000,
        "deaths_b": 4000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 9000,
        "high": 12000,
        "low": 7000,
        "deaths_total": 9000,
        "length_of_conflict": 313,
        "outcome": "Victoria rusa, independencia de estados balcanicos",
        "source_article": "https://en.wikipedia.org/wiki/Russo-Turkish_War_(1877%E2%80%931878)"
    },
    {
        "conflict_id": "INTER_019_BALKAN2",
        "conflict_name": "Second Balkan War",
        "type_of_conflict": "interstate",
        "side_a": "Bulgaria",
        "side_b": "Serbia, Grecia, Rumania, Imperio Otomano",
        "iso_a": "BGR",
        "iso_b": "SRB/GRC/ROU/TUR",
        "date_start": "1913-06-29",
        "date_end": "1913-08-10",
        "latitude": 42.6977,
        "longitude": 23.3219,
        "country": "Bulgaria / Macedonia / Tracia",
        "region": "Europa",
        "deaths_a": 2500,
        "deaths_b": 5500,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 8000,
        "high": 10000,
        "low": 6000,
        "deaths_total": 8000,
        "length_of_conflict": 42,
        "outcome": "Victoria de la Liga Balcanica, derrota bulgara",
        "source_article": "https://en.wikipedia.org/wiki/Second_Balkan_War"
    },
    {
        "conflict_id": "INTER_020_BALKAN1",
        "conflict_name": "First Balkan War",
        "type_of_conflict": "interstate",
        "side_a": "Liga Balcanica (Serbia, Bulgaria, Grecia, Montenegro)",
        "side_b": "Imperio Otomano",
        "iso_a": "SRB/BGR/GRC/MNE",
        "iso_b": "TUR",
        "date_start": "1912-10-08",
        "date_end": "1913-05-30",
        "latitude": 41.9981,
        "longitude": 21.4254,
        "country": "Balcanes",
        "region": "Europa",
        "deaths_a": 3000,
        "deaths_b": 4600,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 7600,
        "high": 10000,
        "low": 6000,
        "deaths_total": 7600,
        "length_of_conflict": 234,
        "outcome": "Victoria de la Liga Balcanica, perdida otomana de territorios europeos",
        "source_article": "https://en.wikipedia.org/wiki/First_Balkan_War"
    },
        {
        "conflict_id": "INTER_021_TRIPLE_ALLIANCE",
        "conflict_name": "War of the Triple Alliance",
        "type_of_conflict": "interstate",
        "side_a": "Paraguay",
        "side_b": "Brasil, Argentina, Uruguay",
        "iso_a": "PRY",
        "iso_b": "BRA/ARG/URY",
        "date_start": "1864-12-13",
        "date_end": "1870-03-01",
        "latitude": -25.2637,
        "longitude": -57.5759,
        "country": "Paraguay, Argentina, Brasil, Uruguay",
        "region": "America del Sur",
        "deaths_a": 3000,
        "deaths_b": 4500,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 7500,
        "high": 10000,
        "low": 6000,
        "deaths_total": 7500,
        "length_of_conflict": 2269,
        "outcome": "Victoria de la Triple Alianza, devastacion de Paraguay",
        "source_article": "https://en.wikipedia.org/wiki/Paraguayan_War"
    },
    {
        "conflict_id": "INTER_022_RUSSO_JAPANESE",
        "conflict_name": "Russo-Japanese War",
        "type_of_conflict": "interstate",
        "side_a": "Imperio Ruso",
        "side_b": "Imperio Japones",
        "iso_a": "RUS",
        "iso_b": "JPN",
        "date_start": "1904-02-08",
        "date_end": "1905-09-05",
        "latitude": 43.1332,
        "longitude": 131.9000,
        "country": "Manchuria / Corea / Japon",
        "region": "Asia Oriental",
        "deaths_a": 3500,
        "deaths_b": 3500,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 7000,
        "high": 9000,
        "low": 6000,
        "deaths_total": 7000,
        "length_of_conflict": 575,
        "outcome": "Victoria japonesa, Tratado de Portsmouth",
        "source_article": "https://en.wikipedia.org/wiki/Russo-Japanese_War"
    },
    {
        "conflict_id": "INTER_023_SINO_VIETNAMESE",
        "conflict_name": "Sino-Vietnamese War",
        "type_of_conflict": "interstate",
        "side_a": "China",
        "side_b": "Vietnam",
        "iso_a": "CHN",
        "iso_b": "VNM",
        "date_start": "1979-02-17",
        "date_end": "1979-03-16",
        "latitude": 21.0285,
        "longitude": 105.8542,
        "country": "China / Vietnam",
        "region": "Asia",
        "deaths_a": 2500,
        "deaths_b": 4000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 6500,
        "high": 8000,
        "low": 5000,
        "deaths_total": 6500,
        "length_of_conflict": 27,
        "outcome": "Retirada china, victoria estrategica vietnamita",
        "source_article": "https://en.wikipedia.org/wiki/Sino-Vietnamese_War"
    },
    {
        "conflict_id": "INTER_024_GULF",
        "conflict_name": "Gulf War",
        "type_of_conflict": "interstate",
        "side_a": "Coalicion Internacional liderada por EE.UU.",
        "side_b": "Irak",
        "iso_a": "USA/SAU/KWT/etc",
        "iso_b": "IRQ",
        "date_start": "1990-08-02",
        "date_end": "1991-02-28",
        "latitude": 29.3759,
        "longitude": 47.9774,
        "country": "Kuwait / Irak",
        "region": "Medio Oriente",
        "deaths_a": 500,
        "deaths_b": 5500,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 6000,
        "high": 8000,
        "low": 4000,
        "deaths_total": 6000,
        "length_of_conflict": 210,
        "outcome": "Victoria de la Coalicion, liberacion de Kuwait",
        "source_article": "https://en.wikipedia.org/wiki/Gulf_War"
    },
    {
        "conflict_id": "INTER_025_IRAQ_KURD1",
        "conflict_name": "First Iraq-Kurd War",
        "type_of_conflict": "interstate",
        "side_a": "Irak",
        "side_b": "Insurgentes kurdos",
        "iso_a": "IRQ",
        "iso_b": "KUR",
        "date_start": "1961-09-11",
        "date_end": "1970-03-11",
        "latitude": 36.1911,
        "longitude": 44.0092,
        "country": "Irak (Region del Kurdistan)",
        "region": "Medio Oriente",
        "deaths_a": 3000,
        "deaths_b": 2500,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 5500,
        "high": 7000,
        "low": 4000,
        "deaths_total": 5500,
        "length_of_conflict": 3103,
        "outcome": "Acuerdo de Autonomia de 1970",
        "source_article": "https://en.wikipedia.org/wiki/First_Iraqi%E2%80%93Kurdish_War"
    },
    {
        "conflict_id": "INTER_027_IRAQ_KURD2",
        "conflict_name": "Second Iraq-Kurd War",
        "type_of_conflict": "interstate",
        "side_a": "Irak",
        "side_b": "Insurgentes kurdos",
        "iso_a": "IRQ",
        "iso_b": "KUR",
        "date_start": "1974-03-06",
        "date_end": "1975-03-31",
        "latitude": 36.2063,
        "longitude": 44.0089,
        "country": "Irak (Region del Kurdistan)",
        "region": "Medio Oriente",
        "deaths_a": 2000,
        "deaths_b": 2500,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 4500,
        "high": 6000,
        "low": 3000,
        "deaths_total": 4500,
        "length_of_conflict": 390,
        "outcome": "Derrota kurda, acuerdos con Iran",
        "source_article": "https://en.wikipedia.org/wiki/Second_Iraqi%E2%80%93Kurdish_War"
    },
    {
        "conflict_id": "INTER_028_SINO_INDIAN",
        "conflict_name": "Sino-Indian War",
        "type_of_conflict": "interstate",
        "side_a": "China",
        "side_b": "India",
        "iso_a": "CHN",
        "iso_b": "IND",
        "date_start": "1962-10-20",
        "date_end": "1962-11-21",
        "latitude": 28.0000,
        "longitude": 91.5000,
        "country": "Himalaya (Aksai Chin, Arunachal Pradesh)",
        "region": "Asia",
        "deaths_a": 700,
        "deaths_b": 3500,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 4200,
        "high": 5000,
        "low": 3500,
        "deaths_total": 4200,
        "length_of_conflict": 32,
        "outcome": "Victoria china, control de Aksai Chin",
        "source_article": "https://en.wikipedia.org/wiki/Sino-Indian_War"
    },
    {
        "conflict_id": "INTER_029_BAR_KOKHBA",
        "conflict_name": "Bar-Kokhba Revolt",
        "type_of_conflict": "interstate",
        "side_a": "Judea",
        "side_b": "Imperio Romano",
        "iso_a": "ISR",
        "iso_b": "ROM",
        "date_start": "132-01-01",
        "date_end": "135-01-01",
        "latitude": 31.7683,
        "longitude": 35.2137,
        "country": "Judea (actual Israel/Palestina)",
        "region": "Medio Oriente",
        "deaths_a": 1000,
        "deaths_b": 3000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 4000,
        "high": 6000,
        "low": 3000,
        "deaths_total": 4000,
        "length_of_conflict": 1095,
        "outcome": "Victoria romana, destruccion de Judea",
        "source_article": "https://en.wikipedia.org/wiki/Bar_Kokhba_revolt"
    },
    {
        "conflict_id": "INTER_030_ITALO_ETHIOPIAN1",
        "conflict_name": "First Italo-Ethiopian War",
        "type_of_conflict": "interstate",
        "side_a": "Italia",
        "side_b": "Etiopia",
        "iso_a": "ITA",
        "iso_b": "ETH",
        "date_start": "1895-12-01",
        "date_end": "1896-10-01",
        "latitude": 9.1450,
        "longitude": 40.4897,
        "country": "Etiopia",
        "region": "Africa",
        "deaths_a": 2000,
        "deaths_b": 2000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 4000,
        "high": 5000,
        "low": 3000,
        "deaths_total": 4000,
        "length_of_conflict": 305,
        "outcome": "Victoria etiope en Adwa, reconocimiento internacional",
        "source_article": "https://en.wikipedia.org/wiki/First_Italo-Ethiopian_War"
    },
    {
        "conflict_id": "INTER_032_HUNGARIAN_INDEP",
        "conflict_name": "Hungarian Independence War",
        "type_of_conflict": "interstate",
        "side_a": "Hungria",
        "side_b": "Imperio Austriaco y Rusia",
        "iso_a": "HUN",
        "iso_b": "AUT/RUS",
        "date_start": "1848-03-15",
        "date_end": "1849-08-13",
        "latitude": 47.4979,
        "longitude": 19.0402,
        "country": "Hungria",
        "region": "Europa Central",
        "deaths_a": 1000,
        "deaths_b": 2000,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 3000,
        "high": 4000,
        "low": 2000,
        "deaths_total": 3000,
        "length_of_conflict": 516,
        "outcome": "Victoria austro-rusa, represion de Hungria",
        "source_article": "https://en.wikipedia.org/wiki/Hungarian_Revolution_of_1848"
    },
    {
        "conflict_id": "INTER_033_AUSTRO_VENETIAN",
        "conflict_name": "Austro-Venetian War",
        "type_of_conflict": "interstate",
        "side_a": "Reino de Cerdeña y Venecia",
        "side_b": "Imperio Austriaco",
        "iso_a": "ITA",
        "iso_b": "AUT",
        "date_start": "1848-03-23",
        "date_end": "1849-08-24",
        "latitude": 45.4408,
        "longitude": 12.3155,
        "country": "Italia (Venecia, Lombardia)",
        "region": "Europa",
        "deaths_a": 1000,
        "deaths_b": 1750,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 2750,
        "high": 3500,
        "low": 2000,
        "deaths_total": 2750,
        "length_of_conflict": 519,
        "outcome": "Victoria austriaca, restauracion de control en el norte de Italia",
        "source_article": "https://en.wikipedia.org/wiki/First_Italian_War_of_Independence"
    },
    {
        "conflict_id": "INTER_034_ITALO_ETHIOPIAN2",
        "conflict_name": "Second Italo-Ethiopian War",
        "type_of_conflict": "interstate",
        "side_a": "Italia",
        "side_b": "Etiopia",
        "iso_a": "ITA",
        "iso_b": "ETH",
        "date_start": "1935-10-03",
        "date_end": "1936-05-09",
        "latitude": 9.1450,
        "longitude": 40.4897,
        "country": "Etiopia",
        "region": "Africa",
        "deaths_a": 1000,
        "deaths_b": 1500,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 2500,
        "high": 4000,
        "low": 2000,
        "deaths_total": 2500,
        "length_of_conflict": 220,
        "outcome": "Victoria italiana, ocupacion de Etiopia",
        "source_article": "https://en.wikipedia.org/wiki/Second_Italo-Ethiopian_War"
    },
    {
        "conflict_id": "INTER_035_ARAB_ISRAELI4",
        "conflict_name": "Fourth Arab-Israeli War (Lebanon 1982)",
        "type_of_conflict": "interstate",
        "side_a": "Israel",
        "side_b": "OLP, Siria, Libano",
        "iso_a": "ISR",
        "iso_b": "PLO/SYR/LBN",
        "date_start": "1982-06-06",
        "date_end": "1982-09-29",
        "latitude": 33.8938,
        "longitude": 35.5018,
        "country": "Libano",
        "region": "Medio Oriente",
        "deaths_a": 500,
        "deaths_b": 1500,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 2000,
        "high": 3000,
        "low": 1500,
        "deaths_total": 2000,
        "length_of_conflict": 115,
        "outcome": "Invasion israeli del sur de Libano, repliegue de la OLP",
        "source_article": "https://en.wikipedia.org/wiki/1982_Lebanon_War"
    },
        {
        "conflict_id": "INTER_036_FALKLANDS",
        "conflict_name": "Falklands/Malvinas War",
        "type_of_conflict": "interstate",
        "side_a": "Argentina",
        "side_b": "Reino Unido",
        "iso_a": "ARG",
        "iso_b": "GBR",
        "date_start": "1982-04-02",
        "date_end": "1982-06-14",
        "latitude": -51.7963,
        "longitude": -59.5236,
        "country": "Islas Malvinas",
        "region": "America del Sur",
        "deaths_a": 649,
        "deaths_b": 255,
        "deaths_civilians": 3,
        "deaths_unknown": 0,
        "best": 2000,
        "high": 2500,
        "low": 1500,
        "deaths_total": 2000,
        "length_of_conflict": 74,
        "outcome": "Victoria britanica, recuperacion de las islas",
        "source_article": "https://en.wikipedia.org/wiki/Falklands_War"
    },
    {
        "conflict_id": "INTER_037_ARAB_ISRAELI3",
        "conflict_name": "Third Arab-Israeli War (Suez Crisis)",
        "type_of_conflict": "interstate",
        "side_a": "Israel, Francia, Reino Unido",
        "side_b": "Egipto",
        "iso_a": "ISR/FRA/GBR",
        "iso_b": "EGY",
        "date_start": "1956-10-29",
        "date_end": "1957-03-07",
        "latitude": 30.0444,
        "longitude": 31.2357,
        "country": "Egipto (Canal de Suez)",
        "region": "Medio Oriente",
        "deaths_a": 500,
        "deaths_b": 1300,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 1800,
        "high": 2500,
        "low": 1500,
        "deaths_total": 1800,
        "length_of_conflict": 129,
        "outcome": "Retirada israeli y franco-britanica bajo presion internacional",
        "source_article": "https://en.wikipedia.org/wiki/Suez_Crisis"
    },
    {
        "conflict_id": "INTER_038_AFGHAN_INVASION",
        "conflict_name": "Invasion of Afghanistan (2001)",
        "type_of_conflict": "interstate",
        "side_a": "Estados Unidos y Coalicion Internacional",
        "side_b": "Talibanes",
        "iso_a": "USA/GBR/etc",
        "iso_b": "AFG",
        "date_start": "2001-10-07",
        "date_end": "2001-12-17",
        "latitude": 34.5553,
        "longitude": 69.2075,
        "country": "Afganistan",
        "region": "Asia Central",
        "deaths_a": 350,
        "deaths_b": 1150,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 1500,
        "high": 2000,
        "low": 1000,
        "deaths_total": 1500,
        "length_of_conflict": 71,
        "outcome": "Caida del regimen taliban, inicio de ocupacion internacional",
        "source_article": "https://en.wikipedia.org/wiki/War_in_Afghanistan_(2001–2021)"
    },
    {
        "conflict_id": "INTER_039_KARGIL",
        "conflict_name": "Kargil War",
        "type_of_conflict": "interstate",
        "side_a": "India",
        "side_b": "Pakistan",
        "iso_a": "IND",
        "iso_b": "PAK",
        "date_start": "1999-05-03",
        "date_end": "1999-07-26",
        "latitude": 34.5570,
        "longitude": 76.1330,
        "country": "Cachemira (Kargil)",
        "region": "Asia Meridional",
        "deaths_a": 527,
        "deaths_b": 646,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 1172,
        "high": 1500,
        "low": 1000,
        "deaths_total": 1172,
        "length_of_conflict": 84,
        "outcome": "Victoria india, retirada paquistani",
        "source_article": "https://en.wikipedia.org/wiki/Kargil_War"
    },
    {
        "conflict_id": "INTER_040_SOUTH_OSSETIA",
        "conflict_name": "South Ossetia War",
        "type_of_conflict": "interstate",
        "side_a": "Georgia",
        "side_b": "Rusia, Osetia del Sur, Abjasia",
        "iso_a": "GEO",
        "iso_b": "RUS/OSS/ABK",
        "date_start": "2008-08-07",
        "date_end": "2008-08-12",
        "latitude": 42.2400,
        "longitude": 43.9700,
        "country": "Georgia (Osetia del Sur, Abjasia)",
        "region": "Europa del Este / Caucaso",
        "deaths_a": 200,
        "deaths_b": 600,
        "deaths_civilians": 198,
        "deaths_unknown": 0,
        "best": 998,
        "high": 1200,
        "low": 800,
        "deaths_total": 998,
        "length_of_conflict": 5,
        "outcome": "Victoria rusa, reconocimiento de Osetia del Sur y Abjasia",
        "source_article": "https://en.wikipedia.org/wiki/2008_Russo-Georgian_war"
    },
        {
        "conflict_id": "INTER_041_SINO_FRENCH",
        "conflict_name": "Sino-French War",
        "type_of_conflict": "interstate",
        "side_a": "China (Dinastia Qing)",
        "side_b": "Francia",
        "iso_a": "CHN",
        "iso_b": "FRA",
        "date_start": "1884-08-23",
        "date_end": "1885-04-09",
        "latitude": 21.0285,
        "longitude": 105.8542,
        "country": "Vietnam (Tonkin), Sur de China",
        "region": "Asia",
        "deaths_a": 400,
        "deaths_b": 500,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 900,
        "high": 1200,
        "low": 800,
        "deaths_total": 900,
        "length_of_conflict": 229,
        "outcome": "Victoria francesa, control de Indochina",
        "source_article": "https://en.wikipedia.org/wiki/Sino-French_War"
    },
    {
        "conflict_id": "INTER_042_KOSOVO",
        "conflict_name": "War for Kosovo",
        "type_of_conflict": "interstate",
        "side_a": "OTAN",
        "side_b": "Serbia (Yugoslavia)",
        "iso_a": "NATO",
        "iso_b": "SRB",
        "date_start": "1999-03-24",
        "date_end": "1999-06-10",
        "latitude": 42.6675,
        "longitude": 21.1662,
        "country": "Kosovo, Serbia",
        "region": "Europa del Este",
        "deaths_a": 200,
        "deaths_b": 700,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 900,
        "high": 1200,
        "low": 700,
        "deaths_total": 900,
        "length_of_conflict": 78,
        "outcome": "Victoria de la OTAN, retirada serbia, administracion internacional en Kosovo",
        "source_article": "https://en.wikipedia.org/wiki/Kosovo_War"
    },
    {
        "conflict_id": "INTER_043_INDOCHINA1",
        "conflict_name": "First Indochina War",
        "type_of_conflict": "interstate",
        "side_a": "Francia",
        "side_b": "Viet Minh",
        "iso_a": "FRA",
        "iso_b": "VNM",
        "date_start": "1946-12-19",
        "date_end": "1954-08-01",
        "latitude": 21.0278,
        "longitude": 105.8342,
        "country": "Vietnam, Laos, Camboya",
        "region": "Asia",
        "deaths_a": 300,
        "deaths_b": 500,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 800,
        "high": 1200,
        "low": 600,
        "deaths_total": 800,
        "length_of_conflict": 2782,
        "outcome": "Victoria del Viet Minh, division de Vietnam",
        "source_article": "https://en.wikipedia.org/wiki/First_Indochina_War"
    },
    {
        "conflict_id": "INTER_044_ITALO_TURKISH",
        "conflict_name": "First Italo-Turkish War",
        "type_of_conflict": "interstate",
        "side_a": "Italia",
        "side_b": "Imperio Otomano",
        "iso_a": "ITA",
        "iso_b": "TUR",
        "date_start": "1911-09-29",
        "date_end": "1912-10-18",
        "latitude": 32.8925,
        "longitude": 13.1800,
        "country": "Libia",
        "region": "Africa del Norte",
        "deaths_a": 300,
        "deaths_b": 400,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 700,
        "high": 1000,
        "low": 500,
        "deaths_total": 700,
        "length_of_conflict": 385,
        "outcome": "Victoria italiana, cesion de Libia y Dodecaneso",
        "source_article": "https://en.wikipedia.org/wiki/Italo-Turkish_War"
    },
    {
        "conflict_id": "INTER_045_SOUTH_AFRICAN1",
        "conflict_name": "First South African War",
        "type_of_conflict": "interstate",
        "side_a": "Boers (Republica Sudafricana)",
        "side_b": "Imperio Britanico",
        "iso_a": "ZAF",
        "iso_b": "GBR",
        "date_start": "1880-12-16",
        "date_end": "1881-03-23",
        "latitude": -25.7479,
        "longitude": 28.2293,
        "country": "Sudafrica",
        "region": "Africa Austral",
        "deaths_a": 300,
        "deaths_b": 360,
        "deaths_civilians": 0,
        "deaths_unknown": 0,
        "best": 660,
        "high": 800,
        "low": 500,
        "deaths_total": 660,
        "length_of_conflict": 97,
        "outcome": "Victoria boer, autonomia limitada para Transvaal",
        "source_article": "https://en.wikipedia.org/wiki/First_Boer_War"
    },
]

# Convertir a DataFrame
df = pd.DataFrame(wars_data)

# Exportar a CSV
df.to_csv("wars_historico_data.csv", index=False, encoding="utf-8")
print("✅ Archivo 'wars_historico_data' creado")
