apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-postgres-pvc
  namespace: wars
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath